<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<!-- Head BEGIN -->

<!-- Mirrored from mel.cgiar.org/index/home/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 09 Mar 2020 11:26:05 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <title>Monitoring, Evaluation and Learning Platform</title>

    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta content="CGIAR Dryland Systems Monitoring, Evaluation and Learning Platform" name="description">
    <meta content="CGIAR Dryland Systems Monitoring, Evaluation and Learning Platform" name="keywords">
    <meta content="ICARDA" name="author">
    <meta http-equiv="cleartype" content="on">

    <!-- BEGIN favicons -->
    <link rel="icon" type="image/png" sizes="196x196" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-192.png">
    <link rel="shortcut icon" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon.ico">
    <link rel="icon" sizes="16x16 32x32 64x64" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon.ico">
    <link rel="icon" type="image/png" sizes="196x196" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-192.png">
    <link rel="icon" type="image/png" sizes="160x160" href="<?= $this->baseUrl(); ?>/frontend/logos/favicons/favicon-160.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $this->baseUrl(); ?>/frontend/logos/favicons/favicon-96.png">
    <link rel="icon" type="image/png" sizes="64x64" href="<?= $this->baseUrl(); ?>/frontend/logos/favicons/favicon-64.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->baseUrl(); ?>/frontend/logos/favicons/favicon-32.png">
    <link rel="icon" type="image/png" sizes="16x16" href=".<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-16.png">
    <link rel="apple-touch-icon" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-72.png">
    <link rel="apple-touch-icon" sizes="144x144" href=".<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-180.png">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="<?= $this->baseUrl(); ?>/assets/frontend/logos/favicons/favicon-180.png">
    <!-- END favicons -->

    <!-- Fonts START -->
    <link
        href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Pathway+Gothic+One|PT+Sans+Narrow:400+700|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all"
        rel="stylesheet" type="text/css">
    <!-- Fonts END -->

    <!-- Global styles BEGIN -->
    <link href="<?= $this->baseUrl(); ?>/assets/global/plugins/bootstrap/css/bootstrap44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/global/plugins/font-awesome/css/font-awesome.mine90a.css?1499857902" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/global/plugins/slider-revolution-slider/rs-plugin/css/settings44a9.css?1491999294"
          rel="stylesheet">
    <!-- Global styles END -->

    <!-- Page level plugin styles BEGIN -->
    <link href="<?= $this->baseUrl(); ?>/assets_v2/global/plugins/fancybox/source/jquery.fancyboxb5ec.css?1491999327" rel="stylesheet">
    <!-- Page level plugin styles END -->

    <!-- Theme styles BEGIN -->
    <link href="<?= $this->baseUrl(); ?>/assets/global/css/components44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/frontend/onepage/css/style44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/frontend/onepage/css/style-responsive44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/frontend/onepage/css/themes/green44a9.css?1491999294" rel="stylesheet" id="style-color">
    <link href="<?= $this->baseUrl(); ?>/assets/frontend/onepage/css/custom44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/global/plugins/bootstrap-treeview/css/bootstrap-treeview44a9.css?1491999294" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery-bootsidemenu/bootsidemenua54b.css?1505052825" rel="stylesheet">
    <link href="<?= $this->baseUrl(); ?>/assets/openview/css/jquery.bxslider44a9.css?1491999294" rel="stylesheet">
    <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/assets/global/plugins/bxslider-4-4.2.15/src/css/jquery.bxslider664f.css?1554631263">

    <style>
        a:hover {
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)"; /* IE 8 */
            filter: alpha(opacity=50); /* IE7 */
            opacity: 0.6;
            text-decoration: none;
        }

        .caption1 {
            position: absolute;
            bottom: 0;
            left: 0;
            z-index: 10;
            color: white;
            background: none repeat scroll 0% 0% rgba(63, 86, 130, 0.57);
            background-color: rgba(19, 19, 21, 0.57);
            background-image: none;
            background-repeat: repeat;
            background-attachment: scroll;
            background-position: 0% 0%;
            background-clip: border-box;
            background-origin: padding-box;
            background-size: auto auto;
            padding: 5px;
        }
        .blog-img {
            height: 250px;
             width: 100%;
        }

        .blog-title {
            color: white;
        }
        .bx-viewport {
            border: none !important;
            box-shadow: none !important;
        }

        .bx-wrapper{
            border: none!important;
            box-shadow: none !important;
            margin-bottom: 0!important;
        }

        .bx-wrapper .bx-viewport {
            position: unset !important;
        }
        .partners-block .img-container {
            display: inline-block;
            min-width: 100px;
            text-align: center;
            padding: 0 10px;
            cursor: pointer;
            transition: all .25s ease-in;
        }
        .partners-block .img-container:hover {
            opacity: .5;
        }
        .partners-block .img-container img {
            height: 65px;
            width: auto;
            border-bottom: solid 1px #eeeeee;
            padding: 0 0 5px 0;
        }
		.top-logo-bar {
    imgheight: 5%;
    width: 5%;
}

    </style>

    <!-- Theme styles END -->
</head>
<body>
<head id="header" class="alt">

<div id="governance" data="home.html">
    <div id="gov_data"></div>
</div>

<!-- Checkout block BEGIN -->
<div id="home-bg">
    <div class="container">
	<!-- Partners block BEGIN -->
<!--<div class="partners-block">-->
<header id="header" class="alt">
<div style="background-color: transparent;">
    <div class="container" style="background-color: transparent;">
	<a target="_blank" href="https://mel.cgiar.org/user/login" class="col-sm-1 col-xs-12 btn red login-btn">Login</a>
        <div class="row text-left">
            <!--<div class="col-md-12 col-xs-12 col-sm-12">-->
               
            <!--</div>-->
			
           <div class="col-md-12 col-sm-12 col-xs-12">
                <p style="font-weight: bold;">Led by:</p>
				<div id="top-logo-bar">
                                    <a class="img-container" target="_blank" href="http://www.rtb.cgiar.org/">
                        <img src="../../graph/getimage/height/100/image/logo-rtb.png" id="top-logo-bar"  height="10%" width="10%" />
                    </a>
                                    <a class="img-container" target="_blank" href="http://gldc.cgiar.org/">
                        <img src="../../graph/getimage/height/100/image/logo-gldc.png" height="10%" width="10%" />
                    </a>
                                    <a class="img-container" target="_blank" href="http://www.worldfishcenter.org/">
                        <img src="../../graph/getimage/height/100/image/logo-fish.png" height="10%" width="10%" />
                    </a>
                                    <a class="img-container" target="_blank" href="http://www.icarda.org/">
                        <img src="../../graph/getimage/height/100/image/logo-icarda2.png" height="10%" width="10%"/>
						   </a>
                                    <a class="img-container" target="_blank" href="http://www.iita.org/">
                        <img src="../../graph/getimage/height/100/image/logo-iita.png" height="10%" width="10%"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://www.icraf.org/">
                        <img src="../../graph/getimage/height/100/image/-partners-1edc8ea6c72eaf1d243e09cc71bb7b52ed3dd2da1449574182.png" height="10%" width="10%"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://cipotato.org/">
                        <img src="../../graph/getimage/height/100/image/logo-cip.png" height="10%" width="10%"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://www.worldfishcenter.org/">
                        <img src="../../graph/getimage/height/100/image/logo-worldfish.png" height="10%" width="10%"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://www.icrisat.org/">
                        <img src="../../graph/getimage/height/100/image/logo-icrasat.png" height="10%" width="10%"/>
                    </a>
					</div>
                            </div>
        </div>
		
<div id="mySidenav" class="sidenav">
<style>
.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: rgba(118,170,229,0.8);
  overflow-x: scroll;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
    transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
    
}
</style>

		
					<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
					
                    <div class="col-md-4 col-sm-6 col-xs-12" id="popover1">
                        <div style="background-color: #EEA33B !important" class="bubble" data-html="true"
                             data-trigger="hover" data-container="body">
                            <strong class="openfacts total">59</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">Reduced Poverty</strong>
                        </div>
                        <div id="ido_0" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased livelihood opportunities
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">18</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">More efficient use of inputs
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">8</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Reduced production risk
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">6</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Diversified enterprise opportunities
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased value capture by producers
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">4</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Reduced pre- and -post production losses, including those
                                                caused by climate change
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Reduce Market Barriers
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Closed yield gaps through improved agronomic and animal
                                                husbandry practices
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased household coping capacity to cope with shocks
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased access to productive assets, including natural
                                                resources
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">4</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Improved access to financial and other services
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enhanced genetic gain
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased conservation and use of genetic resources
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover2">
                        <div style="background-color: #A03826 !important" class="bubble"
                             title="IMPROVED FOOD AND NUTRITION SECURITY AND HEALTH">
                            <strong class="openfacts total">9</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">IMPROVED FOOD AND NUTRITION SECURITY AND
                                HEALTH</strong>
                        </div>
                        <div id="ido_1" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased safe use of inputs
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Reduced biological and chemical hazards in the food system
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased access to diverse nutrient-rich foods
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Optimized consumption of diverse nutrient rich foods
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased availability of diverse nutrient-rich foods
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover3">
                        <div style="background-color: #22465B !important" class="bubble"
                             title="IMPROVED NATURAL RESOURCES SYSTEMS AND ECOSYSTEMS SERVICES.">
                            <strong class="openfacts total">25</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">IMPROVED NATURAL RESOURCES SYSTEMS AND
                                ECOSYSTEMS SERVICES.</strong>
                        </div>
                        <div id="ido_2" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased resilience of agro-ecosystems and communities,
                                                especially those including smallholders
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">10</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Land, water and forest degradation (including
                                                deforestation) minimized and reversed
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">5</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Agricultural systems diversified and intensified in ways
                                                that protect soils and water
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">5</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enhanced adaptive capacity to climate risks
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased genetic diversity of agricultural and associated
                                                landscapes
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">More productive and equitable management of natural
                                                resources
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover4">
                        <div style="background-color: #427730 !important" class="bubble" title="CLIMATE CHANGE">
                            <strong class="openfacts total">3</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">CLIMATE CHANGE</strong>
                        </div>
                        <div id="ido_3" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enabled environment for climate resilience
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enhanced capacity to deal with climate extremes
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Improved forecasting of impacts of climate change and
                                                targeted technology development
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover5">
                        <div style="background-color: #784E28 !important" class="bubble" title="GENDER AND YOUTH">
                            <strong class="openfacts total">4</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">GENDER AND YOUTH</strong>
                        </div>
                        <div id="ido_4" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Improved capacity of women and young people to participate
                                                in decision-making
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Gender-equitable control of productive assets and
                                                resources
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">1</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover6">
                        <div style="background-color: #784E28 !important" class="bubble"
                             title="POLICIES AND INSTITUTIONS">
                            <strong class="openfacts total">19</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr style="margin: 10px 0 !important;">
                            <strong id="slo_name" class="openfacts SLOName">POLICIES AND INSTITUTIONS</strong>
                        </div>
                        <div id="ido_5" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased capacity of beneficiaries to adopt research
                                                outputs
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">13</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Conducive agricultural policy environment
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">3</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					<div class="col-md-4 col-sm-6 col-xs-12" id="popover7">
                        <div style="background-color: #784E28 !important" class="bubble" title="CAPACITY DEVELOPMENT">
                            <strong class="openfacts total">21</strong>
                            <br>
                            <strong>ongoing projects <br></strong>
                            <hr>
                            <strong id="slo_name" class="openfacts SLOName">Capacity Development & Knowledge Sharing</strong>
                        </div>
                        <div id="ido_6" class="hidden-ido">
                            <div id="idoInfo">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th> ido</th>
                                        <th>Ongoing Projects</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enhanced institutional capacity of partner research
                                                organizations
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">6</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Enhanced individual capacity in partner research
                                                organizations through training and exchange
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">7</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased capacity for innovation in partner research
                                                organizations
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">2</div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div id="idoName">Increased capacity for innovation in partner development
                                                organizations and in poor and vulnerable communities
                                            </div>
                                        </td>
                                        <td>
                                            <div id="idoNumber">4</div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
					
					
				
			

    </div>
	<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
			

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
</div>
</header>
</div>

<!-- Partners block END -->
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="col-md-12 home-clear"></div>
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-sm-12  home-section ">
                        <img src="<?= $this->baseUrl(); ?>/assets/frontend/logos/logo.png" alt=""
                             class="col-sm-12 col-xs-12" style="opacity:1;">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-sm-12  home-section ">
                        <span class="home-text">MELSpace is an Open Access repository, it safeguards intellectual property and provides full credit to the authors of knowledge reported. Read and download thousands of researches and tools! </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-sm-12  home-section ">
                        <a target="_blank" href="https://repo.mel.cgiar.org/" class="btn blue mel-repo-btn">Visit MELSpace</a>
                    </div>
                </div>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="col-md-12 home-clear"></div>

                
                    
                    
                    
                    
                    
                    


                </div>

            </div>


        </div>


    </div>
</div>

<br>
<div class="container-fluid about-us news-events">
    <div class="container">
        <div class="row">
            
            <div class="col-md-12">
                <p style="font-weight: bold;">News:</p>
            </div>
        </div>
    </div>
    <div class="container-fluid ">
        <div class="container">
            <ul id="blogCarousel" class="slider3">
                                    <li>
                                                <a target="_blank"
                           href="https://hdl.handle.net/20.500.11766.1/7b831c">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/16415"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title="\93Issues\94: my experience as Quality Assurance Focal Point"
                                       href="https://hdl.handle.net/20.500.11766.1/7b831c">
                                    \93Issues\94: my experience as Quality Assurance Focal Point                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                                    <li>
                                                <a target="_blank"
                           href="https://mel.cgiar.org/projects/-15/39/lets-fly-to-amman-for-the-icarda-geoinformatics-systems-gis-summer-program">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/6667"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title="Let's fly to Amman for the ICARDA Geoinformatics Systems (GIS) Summer Program"
                                       href="https://mel.cgiar.org/projects/-15/39/lets-fly-to-amman-for-the-icarda-geoinformatics-systems-gis-summer-program">
                                    Let's fly to Amman for the ICARDA Geoinformatics Systems (GIS) Summer ...                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                                    <li>
                                                <a target="_blank"
                           href="https://hdl.handle.net/20.500.11766.1/ad7420">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/11682"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title="Adoption of improved potato varieties in Peru by 62% of potato farmers"
                                       href="https://hdl.handle.net/20.500.11766.1/ad7420">
                                    Adoption of improved potato varieties in Peru by 62% of potato farmers                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                                    <li>
                                                <a target="_blank"
                           href="https://hdl.handle.net/20.500.11766.1/2fb317">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/14135"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title=" Improving Food Security and Reducing Poverty through intra-regional Fish Trade in sub Saharan Africa"
                                       href="https://hdl.handle.net/20.500.11766.1/2fb317">
                                     Improving Food Security and Reducing Poverty through intra-regional F...                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                                    <li>
                                                <a target="_blank"
                           href="https://hdl.handle.net/20.500.11766.1/209c16">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/14312"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title="Adoption estimates of improved cassava varieties in nine countries in South and Southeast Asia indicate that 2.7 million hectares are grown using CIAT-related varieties"
                                       href="https://hdl.handle.net/20.500.11766.1/209c16">
                                    Adoption estimates of improved cassava varieties in nine countries in ...                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                                    <li>
                                                <a target="_blank"
                           href="https://hdl.handle.net/20.500.11766.1/8c6769">
                        <img class="blog-img"
                                 src="https://mel.cgiar.org/graph/getcimage/width/360/height/250/report_file_id/14413"/>
                        </a>

                        <div class="caption1">
                            <div class="caption2">
                                <center>
                                    <a class="blog-title" id="img1a" title="Combating Desertification with Knowledge: the African Initiative (AI-CD) Knowledge Hub"
                                       href="https://hdl.handle.net/20.500.11766.1/8c6769">
                                    Combating Desertification with Knowledge: the African Initiative (AI-C...                                    </a>
                                </center>
                            </div>
                        </div>
                    </li>
                            </ul>
        </div>
    </div>
    <br><br><br>
<div class="col-md-12 col-sm-12 col-xs-12">
                <p style="font-weight: bold;">Powered By:</p>
                                    <a class="img-container" target="_blank" href="https://aws.amazon.com/what-is-aws/?nc2=h_ql_le_int">
                        <img src="../../graph/getimage/height/100/image/-partners-MlLini5167PB_AWS_logo_RGB.jpg"/>
                    </a>
                                    <a class="img-container" target="_blank" href="https://duraspace.org/dspace/about/">
                        <img src="../../graph/getimage/height/100/image/-partners-a11CaVUZvhdspace_logo.jpg"/>
                    </a>
                                    <a class="img-container" target="_blank" href="https://dataverse.org/about">
                        <img src="../../graph/getimage/height/100/image/-partners-IiheOj7sV6dataverse_r_project.png"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://codeobia.com/">
                        <img src="../../graph/getimage/height/100/image/-partners-8b17e1bf386f631e5df9e221dc87e79cfb82abaa1470564208.png"/>
                    </a>
                                    <a class="img-container" target="_blank" href="http://immap.org/">
                        <img src="../../graph/getimage/height/100/image/-partners-03a5e8c44127211c4a984662a018188f7619329d1472454593.png"/>
                    </a>
                            </div>
        </div>

</div>



<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<![endif]-->
<script>
    var base_url = "";
    var discussionsHomeLink = '/discussion';
    var userDataLink = '/user/getallusers';
    var discussionCountLink = '/discussion/discussionscount';
    var relatedFilesLink = '/preplanning/relatedfiles';
</script>
<!-- Load JavaScripts at the bottom, because it will reduce page load time -->
<!-- Core plugins BEGIN (For ALL pages) -->
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery-1.11.0.min44a9.js?1491999294" type="text/javascript"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery-migrate-1.2.1.min44a9.js?1491999294" type="text/javascript"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min44a9.js?1491999294"
        type="text/javascript"></script>
<!-- Core plugins END (For ALL pages) -->

<!-- BEGIN RevolutionSlider -->
<script
    src="<?= $this->baseUrl(); ?>/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.plugins.min44a9.js?1491999294"
    type="text/javascript"></script>
<script
    src="<?= $this->baseUrl(); ?>/assets/global/plugins/slider-revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min44a9.js?1491999294"
    type="text/javascript"></script>
<script src="<?= $this->baseUrl(); ?>/assets/frontend/onepage/scripts/revo-ini44a9.js?1491999294" type="text/javascript"></script>
<!-- END RevolutionSlider -->

<!-- Core plugins BEGIN (required only for current page) -->
<script src="<?= $this->baseUrl(); ?>/assets_v2/global/plugins/fancybox/source/jquery.fancybox.packb5ec.js?1491999327"
        type="text/javascript"></script>
<!-- pop up -->
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery.easing44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery.parallax44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/bootstrap-treeview/js/bootstrap-treeview44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery-bootsidemenu/bootsidemenu44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/jquery.scrollTo.min44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/frontend/onepage/scripts/jquery.nav44a9.js?1491999294"></script>
<script src="<?= $this->baseUrl(); ?>/assets/global/scripts/metronic1847.js?1499790556"></script>
<!-- Core plugins END (required only for current page) -->
<!-- Global js BEGIN -->
<script src="<?= $this->baseUrl(); ?>/assets/frontend/onepage/scripts/layout4968.js?1543068150" type="text/javascript"></script>
<script>
    var tLink = '/user/getguesttree';

        jQuery(document).ready(function () {
        $.getJSON(tLink, function (data) {
            $('#gov_data').html(data.data);
            $('#gov_data').treed({openedClass: 'glyphicon-folder-open', closedClass: 'glyphicon-folder-close'});
            var dclickc = $(".tree_f, .tree_c, .tree_p");
            dclickc.dblclick(function () {
                var urlw = $(this).prop('href');
                window.open(urlw, '_blank');
            });
        });
        $('#governance').BootSideMenu({side: "left", autoClose: true});


        
    });
</script>
<script>
    $(document).ready(function () {
        Layout.init();
    });
</script>
<script src="<?= $this->baseUrl(); ?>/assets/global/plugins/bxslider-4-4.2.15/src/js/jquery.bxslider664f.js?1554631263"></script>
<script>
    jQuery(document).ready(function ($) {
        jQuery('#blogCarousel').bxSlider({
            minSlides: 1,
            maxSlides: 4,
            slideWidth: 360,
            controls: $("#blogCarousel li").length > 3,
            infiniteLoop: false,
            hideControlOnEnd: true,
            slideMargin: 10,
            pager: false
        });
    });
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '../../../www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-65705913-1', 'auto');
    ga('send', 'pageview');
</script>
<!-- Global js END -->
</body>

<!-- Mirrored from mel.cgiar.org/index/home/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 09 Mar 2020 11:26:42 GMT -->
</html>
